name: sparow
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - flake8
  - glpk
  - munch
  - numpy
  - parameterized
  - pip 
  - pyomo
  - pytest
  - pytest-cov
  - rich
  - scikit-learn
  - IPython
  - pip:
    - mpi-sppy
